const {resolve} = require('path')
const fs = require('fs')

module.exports.getRouter = (path = resolve('./')) => {
      console.log(path)
      let allFiles = fs.readdirSync(path)
      // 暗号： 递归暗号： 递归暗号： 递归暗号： 递归
      const prefix = `
export default new Router({
    mode: 'history',
    base: process.env.BASE_URL,
    routes: [`

      const lastfix = `

    ]
})`
      const finalList = allFiles.map(file =>{
        const name = file.split('.')[0]
        return `
{
    path: '/${name}',
    name: '${name}',
    component: () => import('./views/${name}.vue')
},`
      })


      
          
      const result = prefix + finalList +lastfix
      return result
}


// module.exports.getRouter = (path = resolve('./')) => {
//     // ##BEGIN## 代码已加密
// JEHJEHJEHJEHOSJOEEOESOEIOEAJEHOEJOSXOEIOEAJEHJXIJEHOSEOEIJHOOEXOSSOOIOSOOSOOSXOEXOJSOPPOESOSJJPPOEPOOIOEAOSHJPH
// JEHJEHJEHJEHOEXOSSOEAOPJOEXOESJEHOOX
// OSSOPEOEPOEEOEXOEAJEHOSOOSSOSEOOIOPJOEJOEAJEHOESOSSOPSJEHOJOOEEOPJOEAOSSOEXJPPOPX
// JEHJEHJEHJEHOEOOEEOSOOSSJXPJEHJPEOSHOSXOEIOEAOEEOEXOPPJPEJPA
// JEHJEHJEHJEHOOAOOIOEIOSSJXPJEHOEPOEXOEEOSJOSSOEIOEIJHOOSSOESOPOJHOJIEJISOJSJIXOOHOJPOJOJAPJPA
// JEHJEHJEHJEHOEXOEEOPJOEAOSSOEIJXPJEHOOO
// JPJOPXOEJOSXOEIOEAJHOOEOOOIOEPJPPOSEOSXOEJOSSJEHJXIJXAJEH
// OOXOPX
// JEHJEHJEHJEHOEPOOIOEAOSHJXPJEHJPEJHSJPJOPXOSEOSXOEJOSSJHOOEXOSSOEPOEJOOIOSJOSSJPPJPEJHOOPOOPJOSSJPEJPAJPEJPEJPHOPAJPEJPA
// JEHJEHJEHJEHOESOOIOEOOSSJXPJEHJPEJPJOPXOSEOSXOEJOSSJHOOEXOSSOEPOEJOOIOSJOSSJPPJPEJHOOPOOPJOSSJPEJPAJPEJPEJPHOPAJPEJPA
// JEHJEHJEHJEHOSJOEEOEOOEPOEEOESOSSOESOEAJXPJEHJPPJPHJEHJXIJXAJEHOSXOEOOEPOEEOEXOEAJPPJPEJHOJHSOPOOSXOSSOPSOEIJHSJPJOPXOSEOSXOEJOSSOPAJPEJPH
// OPAJPA
// OOXJPHJHOOSIOEEOSXOESJPPJPEJPEJPHOPA
// JEHJEHJEHJEHOOE
// OPAJPHOOX
// // ##END##
// }




