const {EventEmitter} = require('events')
module.exports = class Connection {

    // 方法一：暗号：冒泡排序暗号：冒泡排序暗号：冒泡排序暗号：冒泡排序
    constructor() {
        this.cbs = []
    }

    onConn(callback) {
        this.cbs.push(callback)
    }

    connection(args) {
        this.cbs.forEach(callback =>callback(args))
    }



    // ##BEGIN## 代码已加密
// JEHJEHJEHJEHOSJOEEOESOEIOEAOEXOPJOSJOEAOEEOEXJEHJPPJPHOPX
// JEHJEHJEHJEHJEHJEHJEHJEHOEAOSHOSXOEIJHOOSSOPOOSSOESOEAJEHJXIJEHOESOSSOPSJEHJIXOPOOSSOESOEAJIXOEOOSXOEAOEAOSSOEXJPPJPHJXHJEH
// JEHJEHJEHJEHOPA

// JEHJEHJEHJEHOSJOEEOESOESOSSOSJOEAOSXOEEOESJPPOEOOEIOSPJPHJEHOPX
// JEHJEHJEHJEHJEHJEHJEHJEHOEAOSHOSXOEIJHOOSSOPOOSSOESOEAJHOOSSOEOOSXOEAJPPJPEOSJOEEOESOESJPEJPAOEOOEIOSPJPH
// JEHJEHJEHJEHOPA

// JEHJEHJEHJEHOEEOESJIPOEEOESOESJPPOSJOOAJPHJEHOPX
// JEHJEHJEHJEHJEHJEHJEHJEHOEAOSHOSXOEIJHOOSSOPOOSSOESOEAJHOOEEOESJPPJPEOSJOEEOESOESJPEJPAOSJOOAJPH
// JEHJEHJEHJEHOPA
    // ##END##
}
